language: java 

services:
  - docker
  - postgresql

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp ./test/config.travis.json ./test/config.json

script: docker run --rm -v $(pwd):/app -w /app/test thrustjs/thrust-docker /bin/sh -c "thrust install && thrust test.js"

deploy:
  provider: releases
  api_key: $githubToken
  skip_cleanup: true
  on:
    tags: true
